version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: aidr_db
    environment:
      POSTGRES_DB: aidr_db
      POSTGRES_USER: aidr_user
      POSTGRES_PASSWORD: aidr_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aidr_user -d aidr_db"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data: